from typing import Tuple, List


def SET_COLUMNS(
    hidden: str,
    gpo: str,
    lic: str,
    cs_conv: str,
    score: str,
    check: str,
    contract: str,
    claim_nbr: str,
    order_nbr: str,
    invoice_nbr: str,
    invoice_date: str,
    part: str,
    ship_qty: str,
    unit_rebate: str,
    rebate: str,
    name: str,
    addr: str,
    city: str,
    state: str,
    uom: str,
    cost: str,
) -> Tuple[List[str], List[str]]:

    return (
        [
            hidden,
            name,
            addr,
            city,
            state,
            gpo,
            lic,
            score,
            check,
            contract,
            claim_nbr,
            order_nbr,
            invoice_nbr,
            invoice_date,
            part,
            unit_rebate,
            ship_qty,
            uom,
            cs_conv,
            rebate,
            cost,
        ],
        [
            "period",
            "name",
            "addr",
            "city",
            "state",
            "gpo",
            "license",
            "searchScore",
            "check license",
            "contract",
            "claim_nbr",
            "order_nbr",
            "invoice_nbr",
            "invoice_date",
            "part",
            "unit_rebate",
            "ship_qty",
            "uom",
            "ship_qty_as_cs",
            "rebate",
            "cost",
        ],
    )
